In [2]:
import numpy as np

In [3]:
arr= np.arange(5)

In [4]:
arr

array([0, 1, 2, 3, 4])

In [7]:
arr_2d=np.arange(15,30).reshape(5,3)

In [8]:
arr_2d

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [12]:
arr_2d[3:,1:]

array([[25, 26],
       [28, 29]])

In [18]:
arr_2d

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [21]:
arr_2d [2:4,1]

array([22, 25])

In [22]:
arr_2d[:3,2]

array([17, 20, 23])

In [25]:
arr_2d_new=np.random.randint(10,100,(2,4))

In [26]:
arr_2d_new

array([[43, 68, 75, 37],
       [37, 91, 14, 74]])

In [28]:
arr_2d_new[arr_2d_new<90]

array([43, 68, 75, 37, 37, 14, 74])

In [29]:
arr_2d_new>75


array([[False, False, False, False],
       [False,  True, False, False]])

In [30]:
arr_2d

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [35]:
arr_2d[arr_2d<20]=99

arr_2d

In [36]:
arr_2d

array([[99, 99, 99],
       [99, 99, 20],
       [99, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [38]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [42]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [43]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.random.rand(1)

array([0.39039082])

In [47]:
np.random.randn(25)

array([ 0.31697759,  0.83723023,  0.1292248 , -0.16375151,  0.66070666,
       -0.17941063,  1.71617254, -0.86954917,  0.31230004, -0.01383249,
        0.29797535,  0.86143914, -0.2382532 ,  1.45795037, -0.22305461,
        0.02960762,  0.7079639 , -0.61346408,  1.90568688, -0.60489538,
        1.26819728,  1.14751006, -0.07141853,  0.03191778, -0.1501119 ])

In [63]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [64]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [65]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [66]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [67]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [71]:
mat[3][4]

20

In [72]:
mat[:3,1:2].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [73]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [74]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [80]:
sum=0
arr_list=mat.tolist()
for i in range(len(arr_list)):
    for j in range(len(arr_list[i])):
        sum=sum+arr_list[i][j]
print(sum)    

325


In [79]:
mat.tolist()

[[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]]

In [81]:
np.sum(mat)

325

In [82]:
np.std(mat)

7.211102550927978

In [86]:
mat.shape[1]                    

5

In [90]:
np.sum(mat,0)

array([55, 60, 65, 70, 75])

In [ ]:
np.sum(mat,1)

In [5]:
np.random.randn(5)

array([-0.12447528, -1.42906382,  0.61228096, -0.45680938, -0.68685835])