In [7]:
my_tuple=(1,2,3,4)

In [2]:
my_tuple.append(5)

AttributeError: 'tuple' object has no attribute 'append'

In [3]:
my_tuple.add(5)


AttributeError: 'tuple' object has no attribute 'add'

In [8]:
my_tuple=list(my_tuple).append(5)

In [9]:
print(my_tuple)


None


In [10]:
my_tuple=(1,2,3,4)


In [11]:
my_tuple


(1, 2, 3, 4)

In [12]:
my_tuple=tuple(list(my_tuple).append(5))

TypeError: 'NoneType' object is not iterable

In [13]:
my_tuple

(1, 2, 3, 4)

In [14]:
x=list(my_tuple)
x

[1, 2, 3, 4]

In [15]:
x.append(5)
x

[1, 2, 3, 4, 5]

In [16]:
my_tuple=tuple(x)
my_tuple


(1, 2, 3, 4, 5)

In [28]:
[num%2 for num in range(2,10,2)]

[0, 0, 0, 0]

In [46]:
def my_func(param):
    return param**2  
    

In [30]:
my_func(3)

9


In [36]:
my_func([1,2])

[1, 2, 3, 4, 5]


In [47]:
seq=[1,2,3,4,5]
list(map(my_func,seq))

[1, 4, 9, 16, 25]

In [48]:
list (map(lambda n:n*8,seq))

[8, 16, 24, 32, 40]

In [54]:
list(filter(lambda n: n%3==0 , seq))


[3]

In [50]:
seq

[1, 2, 3, 4, 5]

In [55]:
s="random"
d={"k1":2,"k2":2}
   

In [56]:
d.get("k2")

2

In [62]:
d.update({"k4":5})

In [63]:
d

{'k1': 2, 'k2': 5, 'k4': 5}

In [64]:
x=[(1,2),(4,6),(8,9)]


In [65]:
for a,b in x:
    print(a)

1
4
8


In [74]:

list(map(lambda b:b[1], x))

[2, 6, 9]

In [75]:
s="Hi this is Sam"
s.split()

['Hi', 'this', 'is', 'Sam']

In [77]:
lst=[1,2,[3,4],[5,[100,200,['idea']],23,11],1,7]

In [81]:
lst[3][1][2][0]

'idea'

In [1]:
s="idea"
s.startswith("i")

True

In [3]:
seq=['soup','fries','Salad','cake']

list(filter(lambda s:s.lower().startswith("s"), seq))

['soup', 'Salad']

In [21]:
def caught_speeding(s,b):
   return [['NoTicket','SmallTicket'][ (b and s>65) or (not b and s>60)],'BigTicket'] [(b and s>85) or (not b and s>80)]
    

In [23]:
print(caught_speeding(81,False))

BigTicket


In [24]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [1]:
import numpy as np

In [3]:
arr=np.arange(1,10,3)

In [4]:
arr.shape

(3,)

In [5]:
np.ones(2,3)

TypeError: Cannot interpret '3' as a data type

In [6]:
np.ones(2)

array([1., 1.])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [10]:
np.random.rand(2,3)

array([[0.34367079, 0.30173864, 0.66012552],
       [0.04828919, 0.15058306, 0.09651232]])

In [11]:
np.random.randn(2,3)

array([[ 0.48511757, -1.09718175,  0.60305971],
       [-0.44522065,  1.16730013,  0.01740896]])

In [13]:
np.random.randint(2,8,3)

array([6, 4, 7])

In [14]:
arr=np.random.randint(1,100,8)

In [15]:
arr

array([97, 53, 76,  9, 77, 24, 66, 27])

In [16]:
arr.argmax()

0

In [18]:
arr.max()

97

In [19]:
arr.min()

9

In [20]:
arr.argmin()

3

In [21]:
arr1=np.arange(24)

In [22]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
arr.reshape(6,2)

ValueError: cannot reshape array of size 8 into shape (6,2)

In [24]:
arr1.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
arr.shape

(8,)

In [26]:
arr2=arr.reshape(4,2)
arr2.shape
arr2

array([[97, 53],
       [76,  9],
       [77, 24],
       [66, 27]])

In [27]:
arr2.shape

(4, 2)